test::
	perl ./test.pl BetaReduce
	perl ./test.pl BetaReduce h

	perl ./test.pl Fib
	perl ./test.pl Fib h

	perl ./test.pl Reverse
	perl ./test.pl Reverse h

web::
	(cd ../../; make)
	perl ./test.pl Case w
